version: '2'
services:
  ipfs:
    build:
      context: .
      dockerfile: Dockerfile.balena
    restart: unless-stopped
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    privileged: true
    network_mode: host
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:
